# Generated by Django 5.1.9 on 2025-06-11 09:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_navigation",
            field=wagtail.fields.StreamField(
                [("link_section", 9)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.PageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show child pages in dropdown menu",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 1,
                            "help_text": "Maximum depth of child pages to show (1-3 levels)",
                            "max_value": 3,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 1),
                                ("title", 2),
                                ("show_children", 3),
                                ("max_children_depth", 4),
                            ]
                        ],
                        {},
                    ),
                    6: ("wagtail.blocks.URLBlock", (), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 6), ("title", 0)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 5), ("external", 7)]],
                        {"label": "Links", "max_num": None},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("section_heading", 0), ("links", 8)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="primary_navigation",
            field=wagtail.fields.StreamField(
                [("link", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.PageChooserBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show child pages in dropdown menu",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 1,
                            "help_text": "Maximum depth of child pages to show (1-3 levels)",
                            "max_value": 3,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 0),
                                ("title", 1),
                                ("show_children", 2),
                                ("max_children_depth", 3),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Main site navigation",
            ),
        ),
    ]
