# Generated by Django 5.1.9 on 2025-06-07 09:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateField(verbose_name="表演日期")),
                ("event_name", models.CharField(max_length=255, verbose_name="活動名稱")),
                ("event_type", models.CharField(max_length=50, verbose_name="類型")),
                ("venue", models.CharField(max_length=255, verbose_name="地點")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
