# Generated by Django 5.1.9 on 2025-06-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("performances", "0003_city_eventtype_alter_performance_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="city",
            field=models.CharField(max_length=50, verbose_name="城市"),
        ),
        migrations.AlterField(
            model_name="performance",
            name="event_type",
            field=models.CharField(max_length=255, verbose_name="類型"),
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="EventType",
        ),
    ]
