# Generated by Django 5.1.9 on 2025-06-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("performances", "0005_city_eventtype_alter_performance_event_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="city",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="排序順序"),
        ),
    ]
