# Generated by Django 5.1.9 on 2025-06-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("performances", "0006_alter_city_options_city_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventtype",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="eventtype",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="排序順序"),
        ),
    ]
