# Generated by Django 5.1.9 on 2025-09-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("performances", "0008_performancestatspage"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="English Name"
            ),
        ),
    ]
