# Generated by Django 5.1.9 on 2025-09-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("performances", "0009_eventtype_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="English Name"
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="event_name_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="English Event Name"
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="venue_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="English Venue"
            ),
        ),
    ]
