# Generated by Django 5.1.9 on 2025-12-11 14:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("performances", "0010_city_name_en_performance_event_name_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="專輯名稱")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="English Album Name"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序順序")),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReplayPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "listing_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title used when this page appears in listings",
                        max_length=255,
                    ),
                ),
                (
                    "listing_summary",
                    models.CharField(
                        blank=True,
                        help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.",
                        max_length=255,
                    ),
                ),
                (
                    "appear_in_search_results",
                    models.BooleanField(
                        default=True,
                        help_text="Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the image you wish to be displayed when this page appears in listings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "回顧頁面 / Replay Page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="歌曲名稱")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="English Title"
                    ),
                ),
                (
                    "artist",
                    models.CharField(blank=True, max_length=255, verbose_name="演唱者"),
                ),
                (
                    "artist_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="English Artist"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序順序")),
                (
                    "album",
                    models.ForeignKey(
                        default=1,
                        help_text="選擇專輯，預設為單曲",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="performances.album",
                        verbose_name="專輯",
                    ),
                ),
            ],
            options={
                "verbose_name": "歌曲",
                "verbose_name_plural": "歌曲",
                "ordering": ["order", "title"],
            },
        ),
    ]
