# Generated by Django 5.1.9 on 2025-12-11 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("performances", "0011_album_replaypage_song"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Song",
                "verbose_name_plural": "Songs",
            },
        ),
    ]
