# Generated by Django 5.1.9 on 2025-12-14 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("performances", "0012_alter_song_options"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="replaypage",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Logo to display in top left corner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Logo",
            ),
        ),
    ]
