# Generated by Django 5.1.9 on 2025-12-16 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("performances", "0013_replaypage_logo"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                help_text="非必填。建議使用正方形圖片。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="專輯封面",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="single_image",
            field=models.ForeignKey(
                blank=True,
                help_text="如果歌曲被設定為單曲 (Album ID=1)，可選填此欄位。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="單曲封面",
            ),
        ),
    ]
