# Generated by Django 5.1.9 on 2025-12-19 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("performances", "0014_album_cover_image_song_single_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                help_text="非必填。建議使用正方形圖片。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
                verbose_name="專輯封面",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="single_image",
            field=models.ForeignKey(
                blank=True,
                help_text="如果歌曲被設定為單曲 (Album ID=1)，可選填此欄位。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
                verbose_name="單曲封面",
            ),
        ),
    ]
