# Generated by Django 5.1.9 on 2025-12-19 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("performances", "0015_alter_album_cover_image_alter_song_single_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replaypage",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Logo to display in top left corner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
                verbose_name="Logo",
            ),
        ),
    ]
