# Generated by Django 4.2.30 on 2026-09-06 04:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0016_alter_replaypage_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('custom_title', models.CharField(blank=True, help_text='只在曲庫沒有這首歌時填寫。', max_length=255, verbose_name='自訂曲名')),
                ('note', models.CharField(blank=True, help_text='例如「Cover」、「Encore」、「與 XXX 合唱」。', max_length=255, verbose_name='備註')),
                ('performance', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist', to='performances.performance')),
                ('song', models.ForeignKey(blank=True, help_text='從曲庫選一首。翻唱或曲庫沒有的歌請留空，改填下方自訂曲名。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setlist_items', to='performances.song', verbose_name='曲庫歌曲')),
            ],
            options={
                'verbose_name': '曲目',
                'verbose_name_plural': '曲目',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
