# Generated by Django 4.2.30 on 2026-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0017_setlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='setlist_order_uncertain',
            field=models.BooleanField(default=False, help_text='勾選後，前台的歌單標記會改用淺黃色，表示曲序未經確認。', verbose_name='不確定順序'),
        ),
    ]
