# Generated by Django 4.2.30 on 2026-09-07 13:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('performances', '0018_performance_setlist_order_uncertain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetlistProgressPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.", max_length=255)),
                ('appear_in_search_results', models.BooleanField(default=True, help_text='Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('donation_amount', models.PositiveIntegerField(default=10, help_text='顯示在號召文字裡的金額。', verbose_name='每份歌單捐款金額（新台幣）')),
                ('top_songs_count', models.PositiveIntegerField(default=10, help_text='累積演出次數最高的前幾首。讀者仍可在頁面上切換為全部。', verbose_name='歌曲圖表預設顯示首數')),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'verbose_name': '歌單募集頁',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
