# Generated by Django 4.2.30 on 2026-09-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0019_setlistprogresspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlistprogresspage',
            name='show_donation_call',
            field=models.BooleanField(default=True, help_text='取消勾選後，進度條下方的黃色號召框就不會出現。', verbose_name='顯示捐款號召'),
        ),
        migrations.AlterField(
            model_name='setlistprogresspage',
            name='donation_amount',
            field=models.PositiveIntegerField(default=10, help_text='顯示在號召文字裡的金額。未勾選上方欄位時不會用到。', verbose_name='每份歌單捐款金額（新台幣）'),
        ),
    ]
