# Generated by Django 5.1.9 on 2025-09-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articletopic",
            name="slug_en",
            field=models.SlugField(
                blank=True, max_length=255, verbose_name="English Slug"
            ),
        ),
        migrations.AddField(
            model_name="articletopic",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="English Title"
            ),
        ),
        migrations.AddField(
            model_name="authorsnippet",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="English Title"
            ),
        ),
        migrations.AddField(
            model_name="statistic",
            name="description_en",
            field=models.CharField(
                blank=True, max_length=225, verbose_name="English Description"
            ),
        ),
    ]
