# Generated by Django 5.1.9 on 2025-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0002_articletopic_slug_en_articletopic_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistic",
            name="statistic_en",
            field=models.CharField(
                blank=True, max_length=12, verbose_name="English Statistic"
            ),
        ),
    ]
