# Generated by Django 5.1.9 on 2026-05-08 09:26

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="LyricsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "listing_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title used when this page appears in listings",
                        max_length=255,
                    ),
                ),
                (
                    "listing_summary",
                    models.CharField(
                        blank=True,
                        help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.",
                        max_length=255,
                    ),
                ),
                (
                    "appear_in_search_results",
                    models.BooleanField(
                        default=True,
                        help_text="Make this page available for indexing by search engines.If unchecked, the page will no longer be indexed by search engines.",
                    ),
                ),
                (
                    "artist",
                    models.CharField(blank=True, max_length=255, verbose_name="演唱者"),
                ),
                (
                    "composer",
                    models.CharField(blank=True, max_length=255, verbose_name="作曲"),
                ),
                (
                    "lyricist",
                    models.CharField(blank=True, max_length=255, verbose_name="作詞"),
                ),
                (
                    "release_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="發行年份"
                    ),
                ),
                (
                    "display_mode",
                    models.CharField(
                        choices=[
                            ("bilingual", "雙語對照（中／英）"),
                            ("duet", "對唱模式（A／B）"),
                            ("single", "單欄（只用左欄）"),
                        ],
                        default="bilingual",
                        max_length=20,
                        verbose_name="顯示模式",
                    ),
                ),
                (
                    "left_label",
                    models.CharField(
                        blank=True,
                        default="中文",
                        help_text="顯示在左欄上方，例：中文／Voice A／主唱",
                        max_length=50,
                        verbose_name="左欄標題",
                    ),
                ),
                (
                    "right_label",
                    models.CharField(
                        blank=True,
                        default="English",
                        help_text="顯示在右欄上方。單欄模式時忽略。",
                        max_length=50,
                        verbose_name="右欄標題",
                    ),
                ),
                (
                    "line_height",
                    models.FloatField(
                        default=1.8,
                        help_text="1.0 = 緊密；1.8 = 標準；2.5 以上 = 寬鬆。可填小數，例：1.6",
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(3.5),
                        ],
                        verbose_name="行距倍數",
                    ),
                ),
                (
                    "line_gap",
                    models.PositiveIntegerField(
                        default=8,
                        help_text="兩行歌詞之間的額外空隙。設 0 就只靠 line-height 撐開。",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(48),
                        ],
                        verbose_name="歌詞行間距 (px)",
                    ),
                ),
                (
                    "section_gap",
                    models.PositiveIntegerField(
                        default=32,
                        help_text="主歌、副歌等段落之間的距離。",
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(96),
                        ],
                        verbose_name="段落間距 (px)",
                    ),
                ),
                (
                    "column_gap",
                    models.PositiveIntegerField(
                        default=32,
                        help_text="左右兩欄之間的水平距離。",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="左右欄間距 (px)",
                    ),
                ),
                (
                    "font_size",
                    models.PositiveIntegerField(
                        default=18,
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(32),
                        ],
                        verbose_name="歌詞字級 (px)",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("section", 6), ("note", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "例：Verse 1、Chorus、Bridge、Outro",
                                    "label": "段落名稱",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "若雙語想要兩種寫法，例：左『主歌』右『Verse』。留空則沿用左欄。",
                                    "label": "段落名稱（右欄）",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "這一行的中文／主唱。可留空（讓對方獨唱）。",
                                    "label": "左欄",
                                    "required": False,
                                    "rows": 2,
                                },
                            ),
                            3: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "這一行的英文／合音。可留空。",
                                    "label": "右欄",
                                    "required": False,
                                    "rows": 2,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("left", 2), ("right", 3)]],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.ListBlock",
                                (4,),
                                {"label": "歌詞行", "min_num": 1},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("section_name", 0),
                                        ("section_name_alt", 1),
                                        ("lines", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "不屬於歌詞主體的補充文字，例：原作者註、翻譯者說明。",
                                    "label": "註解 / 備註",
                                    "required": False,
                                },
                            ),
                        },
                        verbose_name="歌詞內容",
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the image you wish to be displayed when this page appears in listings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "歌詞頁",
                "verbose_name_plural": "歌詞頁",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
