# Generated by Django 5.1.9 on 2025-06-05 18:23

import wagtail_color_panel.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("standardpages", "0005_alter_indexpage_body_alter_standardpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexpage",
            name="color",
            field=wagtail_color_panel.fields.ColorField(
                default="#000000", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="color",
            field=wagtail_color_panel.fields.ColorField(
                default="#000000", max_length=7
            ),
        ),
    ]
