# Generated by Django 5.1.9 on 2025-06-14 05:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("standardpages", "0009_alter_indexpage_body_alter_standardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("section", 4), ("cta", 16), ("statistics", 20)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "required": False,
                            "template": "components/streamfield/blocks/heading2_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "h3",
                                "embed",
                            ],
                            "template": "components/streamfield/blocks/paragraph_block.html",
                        },
                    ),
                    2: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "貼上 YouTube、Vimeo 或其他影片網址",
                            "icon": "media",
                            "label": "嵌入影片",
                        },
                    ),
                    3: (
                        "wagtail.blocks.StreamBlock",
                        [[("paragraph", 1), ("embed", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "icon": "title", "required": True},
                    ),
                    6: ("wagtail.blocks.PageChooserBlock", (), {}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show child pages in dropdown menu",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 1,
                            "help_text": "Maximum depth of child pages to show (1-3 levels)",
                            "max_value": 3,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 6),
                                ("title", 7),
                                ("show_children", 8),
                                ("max_children_depth", 9),
                            ]
                        ],
                        {},
                    ),
                    11: ("wagtail.blocks.URLBlock", (), {}),
                    12: ("wagtail.blocks.CharBlock", (), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 11), ("title", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 10), ("external", 13)]],
                        {},
                    ),
                    15: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 5), ("link", 14), ("description", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If checked, the heading will be hidden from view and avaliable to screen-readers only.",
                            "label": "Screen reader only label",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("utils.Statistic",),
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ListBlock",
                        (18,),
                        {"max_num": 3, "min_num": 3},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 5), ("sr_only_label", 17), ("statistics", 19)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("section", 4), ("cta", 16), ("statistics", 20)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "required": False,
                            "template": "components/streamfield/blocks/heading2_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "h3",
                                "embed",
                            ],
                            "template": "components/streamfield/blocks/paragraph_block.html",
                        },
                    ),
                    2: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "貼上 YouTube、Vimeo 或其他影片網址",
                            "icon": "media",
                            "label": "嵌入影片",
                        },
                    ),
                    3: (
                        "wagtail.blocks.StreamBlock",
                        [[("paragraph", 1), ("embed", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "icon": "title", "required": True},
                    ),
                    6: ("wagtail.blocks.PageChooserBlock", (), {}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show child pages in dropdown menu",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 1,
                            "help_text": "Maximum depth of child pages to show (1-3 levels)",
                            "max_value": 3,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 6),
                                ("title", 7),
                                ("show_children", 8),
                                ("max_children_depth", 9),
                            ]
                        ],
                        {},
                    ),
                    11: ("wagtail.blocks.URLBlock", (), {}),
                    12: ("wagtail.blocks.CharBlock", (), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 11), ("title", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 10), ("external", 13)]],
                        {},
                    ),
                    15: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 5), ("link", 14), ("description", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If checked, the heading will be hidden from view and avaliable to screen-readers only.",
                            "label": "Screen reader only label",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("utils.Statistic",),
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ListBlock",
                        (18,),
                        {"max_num": 3, "min_num": 3},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 5), ("sr_only_label", 17), ("statistics", 19)]],
                        {},
                    ),
                },
            ),
        ),
    ]
