# Generated by Django 5.1.9 on 2025-06-09 13:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_homepage_body"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="bg_display_mode",
            field=models.CharField(
                choices=[
                    ("cover", "擴展填滿 (cover)"),
                    ("contain", "原圖/等比例顯示 (contain)"),
                    ("repeat", "重複 (repeat)"),
                    ("no-repeat", "原圖不重複 (no-repeat)"),
                ],
                default="cover",
                max_length=20,
                verbose_name="顯示方式",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="bg_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="背景圖片",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="bg_opacity",
            field=models.IntegerField(default=60, help_text="透明度0=全透明; 100=不透明"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("section", 3), ("cta", 13), ("statistics", 17)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "template": "components/streamfield/blocks/heading2_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "h3",
                                "embed",
                            ],
                            "template": "components/streamfield/blocks/paragraph_block.html",
                        },
                    ),
                    2: ("wagtail.blocks.StreamBlock", [[("paragraph", 1)]], {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "icon": "title", "required": True},
                    ),
                    5: ("wagtail.blocks.PageChooserBlock", (), {}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 5), ("title", 6)]],
                        {},
                    ),
                    8: ("wagtail.blocks.URLBlock", (), {}),
                    9: ("wagtail.blocks.CharBlock", (), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 8), ("title", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 7), ("external", 10)]],
                        {},
                    ),
                    12: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("link", 11), ("description", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If checked, the heading will be hidden from view and avaliable to screen-readers only.",
                            "label": "Screen reader only label",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("utils.Statistic",),
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {"max_num": 3, "min_num": 3},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("sr_only_label", 14), ("statistics", 16)]],
                        {},
                    ),
                },
            ),
        ),
    ]
