# Generated by Django 5.1.9 on 2025-06-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_homepage_bg_display_mode_homepage_bg_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="bg_opacity",
            field=models.IntegerField(default=60, help_text="透明度，0=全透明，100=不透明"),
        ),
    ]
