# Generated by Django 5.1.9 on 2025-06-09 14:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_homepage_bg_opacity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="bg_display_mode",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="bg_image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="bg_opacity",
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=wagtail.fields.StreamField(
                [("image", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If left blank, the image's global alt text will be used.",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 0), ("image_alt_text", 1), ("caption", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
