# Generated by Django 5.1.9 on 2025-06-11 09:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_articlepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("section", 3), ("cta", 15), ("statistics", 19)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "template": "components/streamfield/blocks/heading2_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "h3",
                                "embed",
                            ],
                            "template": "components/streamfield/blocks/paragraph_block.html",
                        },
                    ),
                    2: ("wagtail.blocks.StreamBlock", [[("paragraph", 1)]], {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "icon": "title", "required": True},
                    ),
                    5: ("wagtail.blocks.PageChooserBlock", (), {}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show child pages in dropdown menu",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 1,
                            "help_text": "Maximum depth of child pages to show (1-3 levels)",
                            "max_value": 3,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 5),
                                ("title", 6),
                                ("show_children", 7),
                                ("max_children_depth", 8),
                            ]
                        ],
                        {},
                    ),
                    10: ("wagtail.blocks.URLBlock", (), {}),
                    11: ("wagtail.blocks.CharBlock", (), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 10), ("title", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 9), ("external", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("link", 13), ("description", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If checked, the heading will be hidden from view and avaliable to screen-readers only.",
                            "label": "Screen reader only label",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("utils.Statistic",),
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {"max_num": 3, "min_num": 3},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("sr_only_label", 16), ("statistics", 18)]],
                        {},
                    ),
                },
            ),
        ),
    ]
