# Generated by Django 5.1.9 on 2025-06-14 06:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0009_alter_articlepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("section", 6), ("cta", 18), ("statistics", 22)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "required": False,
                            "template": "components/streamfield/blocks/heading2_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "h3",
                                "embed",
                            ],
                            "template": "components/streamfield/blocks/paragraph_block.html",
                        },
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "請貼上 YouTube 影片網址（例如：https://www.youtube.com/watch?v=VIDEO_ID）"
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "影片標題（可選）", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("youtube_url", 2), ("title", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StreamBlock",
                        [[("paragraph", 1), ("youtube", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "icon": "title", "required": True},
                    ),
                    8: ("wagtail.blocks.PageChooserBlock", (), {}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show child pages in dropdown menu",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 1,
                            "help_text": "Maximum depth of child pages to show (1-3 levels)",
                            "max_value": 3,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 8),
                                ("title", 9),
                                ("show_children", 10),
                                ("max_children_depth", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.URLBlock", (), {}),
                    14: ("wagtail.blocks.CharBlock", (), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 13), ("title", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 12), ("external", 15)]],
                        {},
                    ),
                    17: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 7), ("link", 16), ("description", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If checked, the heading will be hidden from view and avaliable to screen-readers only.",
                            "label": "Screen reader only label",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("utils.Statistic",),
                        {},
                    ),
                    21: (
                        "wagtail.blocks.ListBlock",
                        (20,),
                        {"max_num": 3, "min_num": 3},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 7), ("sr_only_label", 19), ("statistics", 21)]],
                        {},
                    ),
                },
            ),
        ),
    ]
