# Generated by Django 5.1.9 on 2025-09-19 13:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0012_alter_articlepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("section", 10), ("cta", 22), ("statistics", 26)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "required": False,
                            "template": "components/streamfield/blocks/heading2_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "h3",
                                "embed",
                                "image",
                            ],
                            "template": "components/streamfield/blocks/paragraph_block.html",
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If left blank, the image's global alt text will be used.",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("image_alt_text", 3), ("caption", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "影片標題（可選）", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "請貼上 YouTube 影片網址（支援 youtube.com 和 youtu.be 格式）"},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("youtube_url", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StreamBlock",
                        [[("paragraph", 1), ("image", 5), ("youtube", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "icon": "title", "required": True},
                    ),
                    12: ("wagtail.blocks.PageChooserBlock", (), {}),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show child pages in dropdown menu",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 1,
                            "help_text": "Maximum depth of child pages to show (1-3 levels)",
                            "max_value": 3,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("page", 12),
                                ("title", 13),
                                ("show_children", 14),
                                ("max_children_depth", 15),
                            ]
                        ],
                        {},
                    ),
                    17: ("wagtail.blocks.URLBlock", (), {}),
                    18: ("wagtail.blocks.CharBlock", (), {}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 17), ("title", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 16), ("external", 19)]],
                        {},
                    ),
                    21: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 11), ("link", 20), ("description", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If checked, the heading will be hidden from view and avaliable to screen-readers only.",
                            "label": "Screen reader only label",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("utils.Statistic",),
                        {},
                    ),
                    25: (
                        "wagtail.blocks.ListBlock",
                        (24,),
                        {"max_num": 3, "min_num": 3},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 11), ("sr_only_label", 23), ("statistics", 25)]],
                        {},
                    ),
                },
            ),
        ),
    ]
